steps:
    # This step runs the unit tests on the app
    - name: 'golang'
      id: Lint
      args: ['make', 'lint']

    - name: 'golang'
      id: Test
      args: ['make', 'test']
    
    # This step builds the container image.
    - name: 'gcr.io/cloud-builders/docker'
      id: Build
      args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/guestbook-go:$SHORT_SHA'
      - '.'
    #   args: ['make', 'build']
    
    # This step pushes the image to Container Registry
    # The PROJECT_ID and SHORT_SHA variables are automatically
    # replaced by Cloud Build.
    - name: 'gcr.io/cloud-builders/docker'
      id: Push
      args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/guestbook-go:$SHORT_SHA'
    #   args: ['make', 'push']